data_constraints:
  file_types:
    - CSV
  max_file_size: 100GB

service_agreement:
  max_throughput: 5MB/s
  max_concurrent_ingestions: 16
  storage_space_staging: 500GB
  max_memory: 2GB

executables:
  taxi_data: batchingestapp.py
  some_other_directory: some_other_script.py