data_constraints:
  file_types:
    - CSV
  max_file_size: 500GB

service_agreement:
  max_throughput: 100MB/s
  max_concurrent_ingestions: 24
  storage_space_staging: 900GB
  max_memory: 16GB

executables:
  taxi_data: batchingestapp.py
  some_other_directory: some_other_script.py